---
name: docker-build-push-tag

on:
  push:
    tags:
      - "v*.*.*"
      - "*.*.*"

jobs:
  docker-build-push:
    permissions:
      contents: read
      id-token: write
      packages: write
    uses: strg-at/github-workflows/.github/workflows/docker-build-push-github.yaml@9bd054504d94b0beba7c5601b1096814759f6e2d
    with:
      runner: '["ubuntu-latest"]'
      subpath: app-tag
      file: app-tag/Dockerfile
      context: app-tag
      tags: |
        type=ref,event=tag,priority=300
        ${{ github.sha }}
        type=raw, value=rolling
