---
name: pre-commit

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - .pre-commit-config.yaml

jobs:
  pre-commit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      # https://github.com/marketplace/actions/setup-python
      - name: install python
        id: install-python
        uses: actions/setup-python@83679a892e2d95755f2dac6acb0bfd1e9ac5d548 # v6.1.0
        with:
          cache: pip

      # https://github.com/marketplace/actions/cache
      - name: actions cache
        uses: actions/cache@9255dc7a253b0ccc959486e2bca901246202afeb # v5.0.1
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ steps.install-python.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: install pre-commit
        run: |
          pip install --upgrade pip
          pip install pre-commit
          pre-commit install

      - name: run pre-commit
        run: >
          pre-commit run
          --show-diff-on-failure
          --color=always
          --all-files
