---
name: pre-commit

on:
  pull_request:
    types:
      - opened
      - synchronize
    paths:
      - .pre-commit-config.yaml

jobs:
  pre-commit:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # https://github.com/marketplace/actions/setup-python
      - name: install python
        id: install-python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          cache: pip

      # https://github.com/marketplace/actions/cache
      - name: actions cache
        uses: actions/cache@cdf6c1fa76f9f475f3d7449005a359c84ca0f306 # v5.0.3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ steps.install-python.outputs.python-version }}-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: install pre-commit
        run: |
          pip install --upgrade pip
          pip install pre-commit
          pre-commit install

      - name: run pre-commit
        run: >
          pre-commit run
          --show-diff-on-failure
          --color=always
          --all-files
